<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>4.1.0</version>
		<relativePath/> <!-- lookup parent from repository -->
	</parent>
	<groupId>com.microservices.demo</groupId>
	<artifactId>microservices-demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>microservices-demo</name>
	<description> Microservices demo project for Spring Boot </description>
	<modules>
		<module>ai-generated-tweet-to-kafka-service</module>
		<module>app-config-data</module>
	</modules>
	<packaging>pom</packaging>

	<properties>
		<java.version>25</java.version>
		<maven-compiler-plugin-version>3.15.0</maven-compiler-plugin-version>
		<lombok.version>1.18.46</lombok.version>
		<httpclient5.version>5.6.1</httpclient5.version>
		<openai-java.version>4.41.0</openai-java.version>
		<google-genai.version>1.59.0</google-genai.version>
		<spring-ai.version>2.0.0</spring-ai.version>
		<app-config-data.version>0.0.1-SNAPSHOT</app-config-data.version>
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${lombok.version}</version>
				<scope>provided</scope>
			</dependency>
			<dependency>
				<groupId>org.apache.httpcomponents.client5</groupId>
				<artifactId>httpclient5</artifactId>
				<version>${httpclient5.version}</version>
			</dependency>
			<dependency>
				<groupId>com.openai</groupId>
				<artifactId>openai-java</artifactId>
				<version>${openai-java.version}</version>
			</dependency>
			<dependency>
				<groupId>com.google.genai</groupId>
				<artifactId>google-genai</artifactId>
				<version>${google-genai.version}</version>
			</dependency>
			<dependency>
				<groupId>org.springframework.ai</groupId>
				<artifactId>spring-ai-bom</artifactId>
				<version>${spring-ai.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>com.microservices.demo</groupId>
				<artifactId>app-config-data</artifactId>
				<version>${app-config-data.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${maven-compiler-plugin-version}</version>
				<configuration>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
							<version>${lombok.version}</version>
						</path>
					</annotationProcessorPaths>
					<release>25</release>
				</configuration>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-maven-plugin</artifactId>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>
