ai-generated-tweet-to-kafka-service:
  streaming-data-keywords:
    - Java
    - Microservices
    - Spring
    - Kafka
    - Elasticsearch
  scheduler-duration-sec: 30
  prompt: "Generate a json with 4 elements called createdAt, id, text and user. The user element has also a nested json element called id. For createdAt use a date in format 'EEE MMM dd HH:mm:ss zzz yyyy', example date would be 'Fri Oct 06 14:32:25 UTC 2023', for id use a Java long value, for text use a string including one or more of the keywords: {keywords}. For id field of the user field use a java long values. Only give 1 result in the response."
  keywords-placeholder: '{keywords}'
  open-ai:
    url: "https://api.openai.com/v1/chat/completions"
#    api-key: ${OPENAI_API_KEY}
    api-key: ${OPENAI_API_KEY}
    content-type: "application/json"
    model: "gpt-4o-mini"
    max-completion-tokens: 150
    temperature: 1
    messages:
      - role: "user"
        content:
          - type: "text"
#  ai-service: Google-GenAI
#  ai-service: OpenAI-JavaClient
#  ai-service: SpringAI-OpenAI
  ai-service: SpringAI-DeepSeek
  google-gen-ai:
    projectId: "robotic-haven-471920-m0"
    location: "us-central-1"
    modelName: "gemini-2.0-flash-001"
    max-output-tokens: 150
    temperature: 1
    candidate-count: 1

spring:
  ai:
    openai:
      chat:
        options:
#          api-key: ${OPENAI_API_KEY}
          api-key: ${DEEPSEEK_API_KEY}
#          base-url: "https://api.openai.com"
          base-url: "https://api.deepseek.com"
#          model: "gpt-4o-mini"
          model: "deepseek-chat-model"
          temperature: 1
          maxTokens: 150
    ollama:
      chat:
        base-url: http://localhost:11434
        options:
          model: llama3.1
          temperature: 1
          top-p: 0.95
          num-predict: 150